### ISSUE TITLE
[FEATURE] Add light/dark theme toggle

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/good-first-issue-finder#114]
### Description

A toggle button to enable light theme or dark theme, and also set it to system theme that changes dynamically according to the overall system theme.

- By default set the theme to light/dark according to the user's system theme.
- A toggle button to change the theme.
- Also, it must store the chosen theme in the cache so that the same theme is rendered the next time the app is opened.

**Comment by aparna2071** [comment]
Hey @vikasganiga05 / @schmelto if this issue is unassigned, I will love to contribute.
Can you please assign this to me?

**Comment by schmelto** [comment]
Sure @aparna2071

**Comment by aparna2071** [comment]
Thanks for assigning me

**Comment by aparna2071** [comment]
Hi @schmelto / @vikasganiga05 I have opened PR: Added theme toggle button #137

**Comment by Cahllagerfeld** [comment]
Hey hey, just a small suggestion from my side:
- Instead of having `#000000` as background, can we use a off-black/dark-greyish color `#22272e`
- instead of having `#ffffff` as color, can we please have `#dadada` instead.

In case you need further documentation, have a look at the
- [tailwind-docs for dark-mode](https://tailwindcss.com/docs/dark-mode)
- Or [this Blogpost](https://www.swyx.io/svelte_tailwind_setup#optional-dark-mode), which also relates to Svelte

**Comment by aparna2071** [comment]
Thanks @Cahllagerfeld for your suggestions.

**Comment by uday03meh** [comment]
Is this issue still open? Can I work on this this?

**Comment by aparna2071** [comment]
> Is this issue still open? Can I work on this this?

Hey, I am working on this.

**Comment by Cahllagerfeld** [comment]
I'll take over the PR, as you closed the PR and also didn't answer in #137. If you want to keep working on this, let me know :)
