### ISSUE TITLE
[FEATURE] Show that it is a "friendly" repo

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/good-first-issue-finder#204]
### Description

Show badges for

- has a license
- has code of conduct
- ...?

**Comment by schmelto** [comment]
Maybe this is something we should also discuss on org level? 

My personal preference is not to include badges like license in the readme cause it's already provided by GitHub in the on the right side under the project description. 

But if we want to include the badges we should use a standard design and include them in all repos we have. It's like the gitpod icon that is currently a little bit cluttered due to a inconsistent design.

**Comment by eddiejaoude** [comment]
Sorry Tom, you are correct, I didn't explain myself well. I don't want to duplicate, I meant on the result page for this project, for example

<img width="1621" alt="Screenshot 2022-09-05 at 07 23 28" src="https://user-images.githubusercontent.com/624760/188373904-c3d77c63-f59e-4699-80e7-2efbd6815374.png">

**Comment by schmelto** [comment]
Yes that's an idea I really likes

**Comment by KlausMikhaelson** [comment]
Hey @eddiejaoude I'm a developer and have worked with svelte and would really like to contribute in this feature, can you please assign this to me ?

**Comment by eddiejaoude** [comment]
Thanks Tom 👍

**Comment by KlausMikhaelson** [comment]
Hi just wanna give the update that I am working on it I was just completing the other projects that I had so I am working on it now!

**Comment by KlausMikhaelson** [comment]
I have added the code of conduct badge and now figuring out license one
