### ISSUE TITLE
[Enhancment] Remove system button theme

### ISSUE THREAD

**Issue by RaheemAmer** [EddieHubCommunity/good-first-issue-finder#231]
## Suggestion

1. I don't see a value for that button since there are already two separate buttons for light and dark themes, so a silly suggestion would be to implement the system theme by default with no need for a button once the user enters the website

2. Also, the two buttons are really close and similar to each other which is a little bit annoying to figure out and maybe a bad practice for the Ui 

## Articles
1. https://medium.com/hypersphere-codes/detecting-system-theme-in-javascript-css-react-f6b961916d48
2. https://davidwalsh.name/detect-dark-mode-preference-with-javascript
3. https://dev.to/bibekkakati/system-color-theme-check-in-javascript-1la9

## Screenshots

![image](https://user-images.githubusercontent.com/18606136/193377365-7f4d40f2-bda7-400a-8bc9-208f3359d247.png)

**Comment by xx-abhijeet-xx** [comment]
Can you assign this issue to me? I can solve it!

**Comment by Cahllagerfeld** [comment]
The system setting does exactly what the linked article suggest. It picks and matches that mediaQuery and sets the theme based on that [[1](https://github.com/EddieHubCommunity/good-first-issue-finder/blob/cdd95fa60ed207615b89acbe9c2151af6495d3f4/src/lib/components/theme-switcher.svelte#L26)]. Computers are providing the setting to switch the dark theme based on day time for example, which means the theme of our page changes dynamically based on that setting.

In case we default to this and remove the button, there wouldn't be an option of going back to the system-wide setting.

Because of that, I think we shouldn't delete that option currently.

**Comment by sambhavgupta0705** [comment]
If we are fine with the system button then we should close this issue
