### ISSUE TITLE
adjust favicon & title

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/good-first-issue-finder#43]

**Comment by KendallDoesCoding** [comment]
Do you have a design for the new favicon?

**Comment by Cahllagerfeld** [comment]
Nope I think its still for discussion. The App is currently using the default Svelte-favicon. This should be replaced, everything else is pretty much open for discussion

**Comment by KendallDoesCoding** [comment]
> Nope I think its still for discussion. The App is currently using the default Svelte-favicon. This should be replaced, everything else is pretty much open for discussion

Ok

**Comment by susheelpal** [comment]
is it a duplicate issue of "update favicon file format"??

**Comment by Cahllagerfeld** [comment]
Nope, it isn't 👍 All fine with the issues  🏀 This one is about the icon itself, not the format

**Comment by KendallDoesCoding** [comment]
Can you make a discussion Cahl for ideas for the new favicon?

**Comment by KlausMikhaelson** [comment]
I can create a nice favicon something like a kid holding a search logo I guess it will look better 
I will be really glad if someone can assign it to me

**Comment by Cahllagerfeld** [comment]
Nice Catch @Dharmik48. I think we should use an image/icon from the [branding repo](https://github.com/EddieHubCommunity/Branding), also to be consistent across Eddiehub Projects (see [LinkFree](https://www.linkfree.eddiehub.io)).

For the given reason, I think creating a custom one is currently not necessary @KlausMikhaelson. In case we decide to go with a custom one later, we can come back to this I think

**Comment by Dharmik48** [comment]
Thank you assigning this me @Cahllagerfeld 

I think we should go with this one because it seems like Hubber is doing some work on the laptop or _searching_ for something, and that's exactly what the users are doing on the website, they are _searching_ for an issue to contribute to. So it feels more meaningful to use this rather than the one I mentioned above

What do you think about this?

![image](https://user-images.githubusercontent.com/64529217/176086524-0be860b1-bd83-402a-94c8-4a06eda7a54b.png)

**Comment by Cahllagerfeld** [comment]
Sure, lets go with this 👍

**Comment by Dharmik48** [comment]
Alright then, I'll get working 💪🏻
